CREATE TABLE IF NOT EXISTS crimes
	( id INTEGER PRIMARY KEY NOT NULL
	, title TEXT
	, latitude FLOAT NOT NULL
	, longitude FLOAT NOT NULL
	, description TEXT
	, datetime TIMESTAMP
	, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
	, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
	)
