CREATE TABLE IF NOT EXISTS crime_images
	( id INTEGER PRIMARY KEY NOT NULL
	, crimeId INTEGER
	, imagePath TEXT
	, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
	, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
	, FOREIGN KEY (crimeId) REFERENCES crimes (id)
	)
